#!/bin/sh /etc/rc.common

START=99

boot() {
        case $(board_name) in
        edgecore,eap102|\
        yuncore,ax880)
                fw_setenv upgrade_available 0
                # Unset changed flag after sysupgrade complete
                fw_setenv changed
        ;;
        redmi,ax6|\
        xiaomi,ax3600|\
        xiaomi,ax9000)
                # OTA handling should not be used. Reset it just in case.
                fw_setenv flag_ota_reboot 0
                # Not strictly needed but useful to handle partition crash condition
                fw_setenv flag_boot_success 1
        ;;        
        linksys,mx4200v1|\
        linksys,mx4200v2|\
        linksys,mx4300|\
        linksys,mx5300|\
        linksys,mx8500)
                mtd resetbc s_env || true
        ;;
        netgear,wax620|\
        netgear,wax630)
                fw_setenv boot_count 0
        ;;
        esac
}
