# by Manper 20250520

include $(TOPDIR)/rules.mk

PKG_NAME:=luci-app-Airpifanctrl
PKG_VERSION:=1.2
PKG_RELEASE:=1

LUCI_TITLE:=LuCI for Airpifanctrl
LUCI_PKGARCH:=all
LUCI_DEPENDS:=+kmod-Airpi-gpio-fan

include $(TOPDIR)/feeds/luci/luci.mk

# $(eval $(call BuildPackage,luci-app-Airpifanctrl)
